#cloud-config

coreos:
  update:
    reboot-strategy: etcd-lock
  etcd2:
    discovery: "${discovery_url}"
    advertise-client-urls: "http://$private_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    listen-client-urls: "http://0.0.0.0:2379"
    listen-peer-urls: "http://$private_ipv4:2380"

  units:
    - name: etcd.service
      mask: true
    - name: etcd2.service
      command: "start"
    - name: flanneld.service
      command: "start"
      drop-ins:
        - name: 10-etcd.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl \
            set /coreos.com/network/config '{ "Network": "${flannel_cidr}", "Backend":{"Type":"vxlan"}}'
