#cloud-config

coreos:
  update:
    reboot-strategy: etcd-lock
  locksmith:
    group: "etcd"
  flannel:
    interface: $private_ipv4
    etcd_endpoints: "http://$private_ipv4:2379"
  etcd2:
    discovery: "${discovery_url}"
    advertise-client-urls: "http://$private_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    listen-client-urls: "http://0.0.0.0:2379"
    listen-peer-urls: "http://$private_ipv4:2380"

  units:
    - name: etcd.service
      mask: true
    - name: format-etcd2-data.service
      content: |
        [Unit]
        Description=Format (if necessary) the etcd2 data
        Wants=dev-xvdh.device
        After=dev-xvdh.device

        [Service]
        Type=oneshot
        ExecStart=/bin/sh -c "blkid -o value -s TYPE /dev/xvdh | grep -q ext4 || mkfs.ext4 -L etcd-data -m 0 /dev/xvdh"
        RemainAfterExit=yes
    - name: var-lib-etcd2.mount
      content: |
        [Unit]
        Requires=format-etcd2-data.service
        After=format-etcd2-data.service
        [Mount]
        What=/dev/xvdh
        Where=/var/lib/etcd2
        Type=ext4
    - name: fix-etcd2-data-permissions.service
      content: |
        [Unit]
        Description="Fix the permissions for the etcd2 data dir"
        Requires=var-lib-etcd2.mount
        After=var-lib-etcd2.mount

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/chown -R etcd: /var/lib/etcd2
        RemainAfterExit=yes
    - name: etcd2.service
      command: "start"
      drop-ins:
        - name: 10-require-data-mount.conf
          content: |
            [Unit]
            Requires=fix-etcd2-data-permissions.service
            After=fix-etcd2-data-permissions.service
    - name: flanneld.service
      command: "restart"
      drop-ins:
        - name: 10-etcd.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config \
              '{ "Network": "${flannel_cidr}", "Backend":{"Type":"vxlan"}}'
